export const SEARCH_JOBS = 'SEARCH_JOBS';
export const NEXT_CATEGORY = 'NEXT_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_RETURNED_CATEGORIES = 'SET_RETURNED_CATEGORIES';
export const SET_NOTADDED_CATEGORIES = 'SET_NOTADDED_CATEGORIES';
export const DELETE_NOTADDED_CATEGORY = 'DELETE_NOTADDED_CATEGORY';